export const money = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
});

export const number = new Intl.NumberFormat('en-US');

export const formatDate = (value) => {
  if (!value) return 'Not available';
  return new Date(value).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
};

export const styles = {
  shell: {
    display: 'grid',
    gridTemplateColumns: '280px minmax(0, 1fr)',
    gap: '2rem',
    paddingTop: '2rem',
    paddingBottom: '5rem',
  },
  sidebar: {
    position: 'sticky',
    top: 96,
    alignSelf: 'start',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '2rem',
    color: 'var(--text-primary)',
    fontWeight: 800,
    fontSize: '1.05rem',
  },
  navCard: {
    padding: '0.75rem',
    borderRadius: 'var(--radius-md)',
    background: 'rgba(10, 16, 30, 0.82)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    boxShadow: 'var(--shadow-md)',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.9rem',
    width: '100%',
    padding: '0.9rem 1rem',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-secondary)',
    fontWeight: 600,
    marginBottom: '0.4rem',
    background: 'transparent',
  },
  navActive: {
    background: 'rgba(99, 102, 241, 0.14)',
    color: 'var(--text-primary)',
    border: '1px solid rgba(99, 102, 241, 0.24)',
  },
  navIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(255, 255, 255, 0.06)',
    boxShadow: 'var(--shadow-sm)',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '1rem',
    marginBottom: '2rem',
  },
  breadcrumb: {
    color: 'var(--text-muted)',
    fontSize: '0.9rem',
    marginBottom: '0.3rem',
  },
  pageTitle: {
    fontSize: '1.7rem',
    margin: 0,
  },
  livePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.45rem',
    color: '#bae6fd',
    background: 'rgba(14, 165, 233, 0.12)',
    border: '1px solid rgba(14, 165, 233, 0.28)',
    borderRadius: 'var(--radius-full)',
    padding: '0.55rem 0.85rem',
    fontSize: '0.8rem',
    fontWeight: 700,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, minmax(170px, 1fr))',
    gap: '1.5rem',
    marginBottom: '1.5rem',
  },
  kpi: {
    minHeight: 118,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '1rem',
    padding: '1.15rem',
    borderRadius: 'var(--radius-lg)',
    background: 'rgba(17, 24, 39, 0.74)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    boxShadow: 'var(--shadow-md)',
  },
  kpiIcon: {
    width: 56,
    height: 56,
    borderRadius: 12,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  metricLabel: {
    color: 'var(--text-secondary)',
    fontSize: '0.9rem',
    fontWeight: 700,
  },
  metricValue: {
    display: 'block',
    marginTop: '0.35rem',
    fontFamily: 'var(--font-heading)',
    fontSize: '1.7rem',
    lineHeight: 1,
  },
  metricMeta: {
    display: 'block',
    marginTop: '0.35rem',
    color: 'var(--text-muted)',
    fontSize: '0.78rem',
  },
  wideGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.35fr) minmax(340px, 0.95fr)',
    gap: '1.5rem',
    marginBottom: '1.5rem',
  },
  bottomGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1.5rem',
  },
  panel: {
    minHeight: 142,
    padding: '1.6rem',
    borderRadius: 'var(--radius-lg)',
    background: 'rgba(17, 24, 39, 0.74)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    boxShadow: 'var(--shadow-md)',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    marginBottom: '1.25rem',
  },
  panelTitle: {
    fontSize: '1.15rem',
    margin: 0,
  },
  viewAll: {
    border: 'none',
    background: 'transparent',
    color: 'var(--color-primary)',
    fontSize: '0.88rem',
    fontWeight: 800,
    cursor: 'pointer',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '0.85rem 1rem',
    borderBottom: '1px solid var(--border-color)',
    color: '#94a3b8',
    fontSize: '0.78rem',
    textTransform: 'uppercase',
    textAlign: 'left',
  },
  td: {
    padding: '0.85rem 1rem',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
    color: 'var(--text-secondary)',
    fontSize: '0.88rem',
  },
  miniRow: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '0.85rem',
    padding: '0.75rem 0',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 10,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    background: 'linear-gradient(135deg, var(--color-primary), var(--color-accent))',
    fontWeight: 800,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: 999,
    padding: '0.25rem 0.6rem',
    fontSize: '0.72rem',
    fontWeight: 800,
    textTransform: 'capitalize',
  },
  empty: {
    padding: '2rem 0',
    color: 'var(--text-muted)',
    textAlign: 'center',
  },
  actionRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '0.5rem',
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    border: '1px solid var(--border-color)',
    background: 'rgba(255,255,255,0.05)',
    color: 'var(--text-primary)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  dangerButton: {
    color: '#f87171',
    borderColor: 'rgba(248, 113, 113, 0.25)',
    background: 'rgba(248, 113, 113, 0.08)',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '0.75rem',
    marginBottom: '1rem',
  },
  input: {
    width: '100%',
    padding: '0.72rem 0.85rem',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border-color)',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-body)',
  },
};

export const tones = [
  { background: 'linear-gradient(135deg, #d946ef, #7c3aed)', color: '#fff' },
  { background: 'linear-gradient(135deg, #60a5fa, #334155)', color: '#fff' },
  { background: 'linear-gradient(135deg, #1f2937, #111827)', color: '#fff' },
  { background: 'linear-gradient(135deg, #fb923c, #ef4444)', color: '#fff' },
  { background: 'linear-gradient(135deg, #84cc16, #16a34a)', color: '#fff' },
];

export const roleColors = {
  admin: { color: '#fbbf24', background: 'rgba(245, 158, 11, 0.13)' },
  instructor: { color: '#38bdf8', background: 'rgba(14, 165, 233, 0.13)' },
  student: { color: '#34d399', background: 'rgba(16, 185, 129, 0.13)' },
};
